import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Google 2.0</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      {/* <Header */}
      <header className="flex w-full p-5 justify-between text-sm text-gray-700">
        {/* Left Div */}
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>
        {/* Right Div */}
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>
          {/* Icons */}

          {/* Avatar */}
        </div>
      </header>

      {/* Body */}

      {/* Footer */}
    </div>
  );
}
