import { NextPage } from "next";
import Head from "next/head"
import SearchBarMenu from "../components/Search/SearchBarMenu"
import React from "react";
import response from "../response"
import { useRouter } from "next/router"
import SearchResults from "../components/Search/SearchResults"

interface Props {
    results: any;
}

const Search: NextPage<Props> = ({ results }) => {
    const router = useRouter();
    console.log(results);

    return (
        <div className="">
            <Head>
                <title>{router.query.term} - Google Search</title>
                <meta name="description" content="Generated by create next app" />
                {/* <link rel="icon" href="/favicon.ico" /> */}
            </Head>

            <SearchBarMenu />

            {/* Search Results */}
            <SearchResults />
        </div>
    );
}

export default Search;

// Server Side Rendering Next.js
export async function getServerSideProps(context: any) {

    const API_KEY = process.env.REACT_APP_API_KEY
    const CONTEXT_KEY = process.env.REACT_APP_CONTEXT_KEY

    const useDummyData = true;
    const startIndex = context.query.start || "0";

    const data = useDummyData ? response : await fetch(
        `https://www.googleapis.com/customsearch/v1?key=${API_KEY}&cx=${CONTEXT_KEY}&q=${context.query.term}&start=${startIndex}`
    ).then(response => response.json());

    // After Server Render, Pass the Results to Client
    return { props: { results: data } }
}